insert into authors (id, first_name, last_name) values (1, 'Jonathan', 'Matua');
insert into authors (id, first_name, last_name) values (2, 'Ellsworth', 'Sycamore');
insert into authors (id, first_name, last_name) values (3, 'Magdalen', 'Sorley');
insert into authors (id, first_name, last_name) values (4, 'Drusilla', 'Leadstone');
insert into authors (id, first_name, last_name) values (5, 'Timmy', 'Wallsworth');
insert into authors (id, first_name, last_name) values (6, 'Linell', 'Lettington');
insert into authors (id, first_name, last_name) values (7, 'Connie', 'Hamberstone');
insert into authors (id, first_name, last_name) values (8, 'Ericha', 'Algore');
insert into authors (id, first_name, last_name) values (9, 'Zack', 'Bartocci');
insert into authors (id, first_name, last_name) values (10, 'Oralle', 'Mabson');
insert into authors (id, first_name, last_name) values (11, 'Lionello', 'Kynd');
insert into authors (id, first_name, last_name) values (12, 'Leonidas', 'Hollows');
insert into authors (id, first_name, last_name) values (13, 'Lewes', 'Kapelhof');
insert into authors (id, first_name, last_name) values (14, 'Tucky', 'Mephan');
insert into authors (id, first_name, last_name) values (15, 'Anatola', 'Blaise');
insert into authors (id, first_name, last_name) values (16, 'Salim', 'Ciric');
insert into authors (id, first_name, last_name) values (17, 'Adelbert', 'Laidel');
insert into authors (id, first_name, last_name) values (18, 'Stephine', 'Toffanini');
insert into authors (id, first_name, last_name) values (19, 'Normy', 'Spatarul');
insert into authors (id, first_name, last_name) values (20, 'Carmelina', 'Vyvyan');
insert into authors (id, first_name, last_name) values (21, 'Baldwin', 'Boxer');

insert into books (id, price, price_old, title, author_id) values (1, 1000000, 100000, 'The Superman!', 1);
insert into books (id, price, price_old, title, author_id) values (2, 1532, 3835, 'Voltsillam', 16);
insert into books (id, price, price_old, title, author_id) values (3, 1488, 3085, 'Zathin', 12);
insert into books (id, price, price_old, title, author_id) values (4, 2980, 3267, 'Tresom', 15);
insert into books (id, price, price_old, title, author_id) values (5, 2010, 1517, 'Bigtax', 18);
insert into books (id, price, price_old, title, author_id) values (6, 1917, 1207, 'Pannier', 1);
insert into books (id, price, price_old, title, author_id) values (7, 2076, 3697, 'Job', 17);
insert into books (id, price, price_old, title, author_id) values (8, 1934, 3043, 'Viva', 4);
insert into books (id, price, price_old, title, author_id) values (9, 536, 3828, 'Quo Lux', 10);
insert into books (id, price, price_old, title, author_id) values (10, 1202, 3368, 'Lotstring', 11);
insert into books (id, price, price_old, title, author_id) values (11, 1777, 3301, 'Bigtax', 1);
insert into books (id, price, price_old, title, author_id) values (12, 2531, 1356, 'Otcom', 3);
insert into books (id, price, price_old, title, author_id) values (13, 2931, 2516, 'Mat Lam Tam', 21);
insert into books (id, price, price_old, title, author_id) values (14, 1038, 1498, 'Tempsoft', 2);
insert into books (id, price, price_old, title, author_id) values (15, 1199, 3314, 'Lotstring', 11);
insert into books (id, price, price_old, title, author_id) values (16, 1703, 2936, 'Tresom', 15);
insert into books (id, price, price_old, title, author_id) values (17, 1564, 3747, 'Konklab', 1);
insert into books (id, price, price_old, title, author_id) values (18, 1668, 2187, 'Stringtough', 9);
insert into books (id, price, price_old, title, author_id) values (19, 1510, 1699, 'Ronstring', 8);
insert into books (id, price, price_old, title, author_id) values (20, 2484, 3861, 'Treeflex', 14);
insert into books (id, price, price_old, title, author_id) values (21, 583, 1563, 'Tin', 5);
