package com.example.mybookshopapp2.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "books")
@ApiModel(description = "entitiy representing a book")
public class Book {
    @ManyToMany(cascade = CascadeType.ALL)
    @JoinTable(name = "book2user",
            joinColumns = @JoinColumn(name = "book_id"),
            inverseJoinColumns = @JoinColumn(name = "user_id")
    )
    Set<User> users = new HashSet<>();
    //    @ManyToOne
////    @JoinColumn(name = "author_id", referencedColumnName = "id")
//    @JoinTable(name = "book2author",
//            joinColumns = @JoinColumn(name = "book_id"),
//            inverseJoinColumns = @JoinColumn(name = "author_id"))
    @ManyToMany(cascade = CascadeType.ALL/*, fetch = FetchType.EAGER*/)
    @JoinTable(name = "book2author",
            joinColumns = @JoinColumn(name = "book_id"),
            inverseJoinColumns = @JoinColumn(name = "author_id")
    )
    @JsonIgnore
    Set<Author> authors = new HashSet<>();
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private Integer id;
    @ApiModelProperty("date of book publication")
    private Date pubDate;
    @ApiModelProperty("if isBestseller = 1, the book is considered a bestseller")
    private Byte isBestseller;
    @ApiModelProperty("mnemonical identity sequence of characters")
    private String slug;
    @ApiModelProperty("image url")
    private String image;
    @Column(columnDefinition = "TEXT")
    @ApiModelProperty("book description text")
    private String description;
    //    private Author author;
    @ApiModelProperty("book title")
    private String title;
    @Column(name = "price")
    @JsonProperty("price")
    @ApiModelProperty("book price without discount")
    private Integer priceOld;
    @Column(name = "discount")
    @JsonProperty("discount")
    @ApiModelProperty("discount value for book")
    private Double price;
    @ManyToOne
    @JoinTable(name = "book2genre",
            joinColumns = @JoinColumn(name = "book_id"),
            inverseJoinColumns = @JoinColumn(name = "genre_id"))
    private Genre genre;

    public Set<User> getUsers() {
        return users;
    }

    public Book setUsers(Set<User> users) {
        this.users = users;
        return this;
    }

    public Set<Author> getAuthors() {
        return authors;
    }

    public Book setAuthors(Set<Author> authors) {
        this.authors = authors;
        return this;
    }

    public Integer getId() {
        return id;
    }

    public Book setId(Integer id) {
        this.id = id;
        return this;
    }

    public Date getPubDate() {
        return pubDate;
    }

    public Book setPubDate(Date pubDate) {
        this.pubDate = pubDate;
        return this;
    }

    public Byte getIsBestseller() {
        return isBestseller;
    }

    public Book setIsBestseller(Byte isBestseller) {
        this.isBestseller = isBestseller;
        return this;
    }

    public String getSlug() {
        return slug;
    }

    public Book setSlug(String slug) {
        this.slug = slug;
        return this;
    }

    public String getImage() {
        return image;
    }

    public Book setImage(String image) {
        this.image = image;
        return this;
    }

    public String getDescription() {
        return description;
    }

    public Book setDescription(String description) {
        this.description = description;
        return this;
    }

    public String getTitle() {
        return title;
    }

    public Book setTitle(String title) {
        this.title = title;
        return this;
    }

    public Integer getPriceOld() {
        return priceOld;
    }

    public Book setPriceOld(Integer priceOld) {
        this.priceOld = priceOld;
        return this;
    }

    public Double getPrice() {
        return price;
    }

    public Book setPrice(Double price) {
        this.price = price;
        return this;
    }

    public Genre getGenre() {
        return genre;
    }

    public Book setGenre(Genre genre) {
        this.genre = genre;
        return this;
    }

//    public Set<User> getUsers() {
//        return users;
//    }
//
//    public Book setUsers(Set<User> users) {
//        this.users = users;
//        return this;
//    }
//
//    @Override
//    public String toString() {
//        return "Book{" +
//                "id=" + id +
//                ", author=" + author +
//                ", title='" + title + '\'' +
//                ", priceOld='" + priceOld + '\'' +
//                ", price='" + price + '\'' +
//                ", genre=" + genre +
//                ", users=" + users +
//                '}';
//    }
}
